name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      variant:
        description: "Select build variant"
        required: true
        default: "coreRelease"
        type: choice
        options:
          - coreRelease
          - fossRelease
          - gplayRelease
          - coreDebug
          - fossDebug
          - gplayDebug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build selected variant
      run: |
        echo "Building variant: ${{ github.event.inputs.variant }}"
        ./gradlew assemble${{ github.event.inputs.variant }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ github.event.inputs.variant }}-apk
        path: **/build/outputs/apk/**/${{ contains(github.event.inputs.variant, 'Release') && 'release' || 'debug' }}/*.apk
